name: Update Clash Config

on:
  # 定时触发 - 每天的 0 点、8 点、16 点 各执行一次任务
  schedule:
    - cron: '0 0,8,16 * * *'

  # 手动触发
  workflow_dispatch:
    inputs:
      force_update:
        description: '强制更新配置'
        required: false
        default: false
        type: boolean

  # 当脚本文件更新时触发
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/update-config.yml'
      - 'config/**'

# 设置权限
permissions:
  contents: read
  pages: write
  id-token: write

# 确保只有一个部署任务同时运行
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  generate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Set up locale and encoding
        run: |
          sudo apt-get update
          sudo apt-get install -y locales language-pack-zh-hans
          sudo locale-gen zh_CN.UTF-8
          sudo update-locale LANG=zh_CN.UTF-8
          echo "LANG=zh_CN.UTF-8" >> $GITHUB_ENV
          echo "LC_ALL=zh_CN.UTF-8" >> $GITHUB_ENV
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests

      - name: Create output directory
        run: |
          mkdir -p docs

      - name: 'Generate merged config'
        env:
          GITHUB_TOKEN: ${{ secrets.CLASH_GITHUB_TOKEN }}
          REPO_OWNER: ${{ secrets.CLASH_REPO_OWNER }}
          REPO_NAME: ${{ secrets.CLASH_REPO_NAME }}
          AUTH_TOKEN: ${{ secrets.CLASH_AUTH_TOKEN }}
          OUTPUT_DIR: docs
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSFSENCODING: utf-8
          PYTHONUTF8: 1
          LC_ALL: zh_CN.UTF-8
          LANG: zh_CN.UTF-8
        run: |
          export PYTHONIOENCODING=utf-8
          export PYTHONUTF8=1
          python -c "import sys; print('Python encoding:', sys.stdout.encoding)"
          python scripts/merge_clash_config.py &
          python scripts/merge_clash_config_2.py &
          python scripts/merge_clash_config_3.py &

          wait

          # 验证生成的文件编码
          echo "=== 检查生成的文件 ==="
          ls -la docs/
          CONFIG_FILE_Ash="docs/clash-Ash-${AUTH_TOKEN}.yaml"
          if [ -f "$CONFIG_FILE_Ash" ]; then
            file "$CONFIG_FILE_Ash"
            head -3 "$CONFIG_FILE_Ash"
            echo "配置文件生成成功: $CONFIG_FILE_Ash"
          else
            echo "错误: 配置文件 $CONFIG_FILE_Ash 未生成"
            exit 1

          CONFIG_FILE_CornSS="docs/clash-CornSS-${AUTH_TOKEN}.yaml"
          if [ -f "$CONFIG_FILE_CornSS" ]; then
            file "$CONFIG_FILE_CornSS"
            head -3 "$CONFIG_FILE_CornSS"
            echo "配置文件生成成功: $CONFIG_FILE_CornSS"
          else
            echo "错误: 配置文件 $CONFIG_FILE_CornSS 未生成"
            exit 1

          CONFIG_FILE_others="docs/clash-others-${AUTH_TOKEN}.yaml"
          if [ -f "$CONFIG_FILE_others" ]; then
            file "$CONFIG_FILE_others"
            head -3 "$CONFIG_FILE_others"
            echo "配置文件生成成功: $CONFIG_FILE_others"
          else
            echo "错误: 配置文件 $CONFIG_FILE_others 未生成"
            exit 1
          fi

      - name: Generate index page with authentication
        env:
          AUTH_TOKEN: ${{ secrets.CLASH_AUTH_TOKEN }}
        run: |
          # 生成带有实际token的HTML页面
          cat > docs/index.html << 'HTMLEOF'
          <!DOCTYPE html>
          <html lang="zh-CN">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Clash 配置服务</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f5f5f5;
                  }
                  .container {
                      background: white;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 30px;
                  }
                  .config-info {
                      background: #f8f9fa;
                      padding: 20px;
                      border-radius: 8px;
                      margin: 20px 0;
                  }
                  .url-box {
                      background: #e9ecef;
                      padding: 15px;
                      border-radius: 5px;
                      font-family: monospace;
                      word-break: break-all;
                      margin: 10px 0;
                  }
                  .warning {
                      color: #dc3545;
                      background: #f8d7da;
                      padding: 15px;
                      border-radius: 5px;
                      margin: 20px 0;
                  }
                  .success {
                      color: #155724;
                      background: #d4edda;
                      padding: 15px;
                      border-radius: 5px;
                      margin: 20px 0;
                  }
                  .btn {
                      display: inline-block;
                      padding: 10px 20px;
                      background: #007bff;
                      color: white;
                      text-decoration: none;
                      border-radius: 5px;
                      margin: 5px;
                  }
                  .btn:hover {
                      background: #0056b3;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>🚀 Clash 配置整合服务</h1>
                      <p>自动整合多个订阅源的 Clash 配置文件</p>
                  </div>

                  <div class="warning">
                      <h3>⚠️ 重要提醒</h3>
                      <ul>
                          <li>此服务仅供个人使用，请勿分享配置链接</li>
                          <li>配置文件每天0 点、8 点、16 点各更新一次</li>
                          <li>访问配置需要正确的认证参数</li>
                      </ul>
                  </div>
                  
                  <div class="config-info">
                      <h3>📊 配置统计Ash</h3>
                      <div id="stats-Ash">加载中...</div>
                  </div>

                  <div class="success">
                      <h3>📋 使用方法</h3>
                      <p>在 Clash 客户端中添加以下订阅链接：</p>
                      <div class="url-box" id="config-url">
                          https://jy-mar.github.io/clash-yaml-merger/clash-Ash-{your-token}.yaml
                      </div>
                      <p><small>请将 {your-token} 替换为您的实际token</small></p>
                  </div>

                  <div class="config-info">
                      <h3>📊 配置统计CornSS</h3>
                      <div id="stats-CornSS">加载中...</div>
                  </div>
                  
                  <div class="success">
                      <h3>📋 使用方法</h3>
                      <p>在 Clash 客户端中添加以下订阅链接：</p>
                      <div class="url-box" id="config-ex-url">
                          https://jy-mar.github.io/clash-yaml-merger/clash-CornSS-{your-token}.yaml
                      </div>
                      <p><small>请将 {your-token} 替换为您的实际token</small></p>
                  </div>

                  <div class="config-info">
                      <h3>📊 配置统计STC/iKuuu/bestbus</h3>
                      <div id="stats-others">加载中...</div>
                  </div>
                  
                  <div class="success">
                      <h3>📋 使用方法</h3>
                      <p>在 Clash 客户端中添加以下订阅链接：</p>
                      <div class="url-box" id="config-ex-url">
                          https://jy-mar.github.io/clash-yaml-merger/clash-others-{your-token}.yaml
                      </div>
                      <p><small>请将 {your-token} 替换为您的实际token</small></p>
                  </div>
              </div>
              
              <script>
                  // 加载统计信息
                  function fetchStats(version_file_suffix) {
                    fetch('stats' + version_file_suffix + '.json')
                      .then(response => response.json())
                      .then(data => {
                          const statsDiv = document.getElementById('stats' + version_file_suffix);
                          let dateStr = ''
                          const generateDate = new Date(data.generated_at)
                          if (typeof generateDate === 'object' && generateDate instanceof Date) {
                              const yyyy = generateDate.getFullYear()
                              let MM = generateDate.getMonth() + 1
                              MM = MM < 10 ? '0' + MM : MM
                              let dd = generateDate.getDate()
                              dd = dd < 10 ? '0' + dd : dd
                              let HH = generateDate.getHours()
                              HH = HH < 10 ? '0' + HH : HH
                              let mm = generateDate.getMinutes()
                              mm = mm < 10 ? '0' + mm : mm
                              let ss = generateDate.getSeconds()
                              ss = ss < 10 ? '0' + ss : ss
                              dateStr = `${yyyy}-${MM}-${dd} ${HH}:${mm}:${ss}`
                          } else {
                              dateStr = String(data.generated_at)
                          }
                          statsDiv.innerHTML = `
                              <p><strong>代理集数量：</strong> ${data.proxy_providers_count}</p>
                              <p><strong>代理节点数量：</strong> ${data.proxies_count}</p>
                              <p><strong>代理组数量：</strong> ${data.proxy_groups_count}</p>
                              <p><strong>规则数量：</strong> ${data.rules_count}</p>
                              <p><strong>最后更新：</strong> ${dateStr}</p>
                          `;
                      })
                      .catch(error => {
                          document.getElementById('stats' + version_file_suffix).innerHTML = '<p style="color: red;">加载统计信息失败</p>';
                      });
                  }
                  fetchStats('-Ash')
                  fetchStats('-CornSS')
                  fetchStats('-others')
              </script>
          </body>
          </html>
          HTMLEOF

      - name: Create authentication wrapper
        env:
          AUTH_TOKEN: ${{ secrets.CLASH_AUTH_TOKEN }}
        run: |
          # 创建一个简单的认证包装器
          cat > docs/clash.yaml.php << 'EOF'
          <?php
          // 简单的认证检查
          $required_token = getenv('AUTH_TOKEN') ?: 'your-auth-token';
          $provided_token = $_GET['token'] ?? '';

          if ($provided_token !== $required_token) {
              http_response_code(404);
              echo "Not Found";
              exit;
          }

          // 返回配置文件
          header('Content-Type: application/x-yaml');
          header('Content-Disposition: attachment; filename="clash.yaml"');
          readfile('clash.yaml');
          ?>
          EOF

          # 由于GitHub Pages不支持PHP，我们创建一个JavaScript版本
          cat > docs/get-config.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Clash Config</title>
          </head>
          <body>
              <script>
                  const urlParams = new URLSearchParams(window.location.search);
                  const token = urlParams.get('token');
                  
                  if (token) {
                      // 这里应该是您的认证token
                      const validToken = '${AUTH_TOKEN}';
                      if (token === validToken) {
                          // 重定向到实际的配置文件
                          window.location.href = 'clash-${AUTH_TOKEN}.yaml';
                      } else {
                          // 返回404
                          document.body.innerHTML = '<h1>404 Not Found</h1>';
                          document.title = '404 Not Found';
                      }
                  } else {
                      // 返回404
                      document.body.innerHTML = '<h1>404 Not Found</h1>';
                      document.title = '404 Not Found';
                  }
              </script>
          </body>
          </html>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-config

    steps:
      - name: 🧹 Clean up old Deployment Records
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.CLASH_GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true

      - name: ⬆️ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
